apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: new-deploy
  name: new-deploy
spec:
  replicas: 12
  selector:
    matchLabels:
      app: new-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: new-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
#kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
#
#run kubectl top nodes to see the usage
