apiVersion: v1
kind: Pod
metadata:
  name: dev
  labels:
    app: dev
    tier: prod
spec:
  containers:
  - name: dev-container
    image: kodekloud/webapp-delayed-start
    ports:
      - containerPort: 8080
        protocol: TCP
    livenessProbe:
      httpGet:
        path: /live
        port: 8080

apiVersion: v1
kind: Pod
metadata:
  name: prod
  labels:
    app: dev
    tier: prod
spec:
  containers:
  - name: my-prod-con
    image: kodekloud/webapp-delayed-start
    ports:
      - containerPort: 8080
        protocol: TCP
    env:
    - name: APP_START_DELAY
      value: "120"
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
    livenessProbe:
        httpGet:
          path: /live
          port: 8080
        periodSeconds: 3
        initialDelaySeconds: 130
apiVersion: v1
kind: Service
metadata:
  name: nafi-dev-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dev
    tier: prod
  type: NodePort

